language: crystal

services:
  - postgresql
  - redis-server

cache:
  directories:
    - bin
    - lib
    - .shards

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TEST_SUITE=./spec/amber
        - DEPLOY_DIR=bin/linux
        - DEPLOY_STATIC="--static"
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TEST_SUITE=./spec/build_spec.cr
    - os: osx
      env:
        - TEST_SUITE=./spec/amber
        - DEPLOY_DIR=bin/darwin
        - DEPLOY_STATIC=""
    - os: osx
      env:
        - TEST_SUITE=./spec/build_spec.cr

before_script:
  - # HACK: https://apple.stackexchange.com/a/126832
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ln -s /usr/local/Cellar/openssl/1.0.2o_2/bin/openssl /usr/local/bin/openssl; fi
  - # HACK: https://github.com/travis-ci/travis-ci/issues/1875
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services run postgres; fi
  - # HACK: https://gist.github.com/subfuzion/9631143
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew services run redis; fi

script:
  - bin/ameba src/ $TEST_SUITE
  - crystal spec $TEST_SUITE

before_deploy:
  - mkdir -p $DEPLOY_DIR
  - crystal build src/amber/cli.cr -s --release $DEPLOY_STATIC -o $DEPLOY_DIR/amber --no-debug
  - tar -cvzf $DEPLOY_FILENAME $DEPLOY_DIR/amber

deploy:
  provider: releases
  api_key: $API_KEY
  file: $DEPLOY_FILENAME
  skip_cleanup: true
  on:
    branch: stable
    repo: amberframework/amber
    condition: $TEST_SUITE = ./spec/amber

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaf02221d4649d70b384
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
