language: crystal

services:
  - postgresql
  - redis-server

cache:
  directories:
    - bin
    - lib
    - .shards

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TEST_SUITE=./spec/amber
        - DEPLOY_DIR=bin/linux
        - DEPLOY_STATIC="--static"
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TEST_SUITE=./spec/build_spec.cr
    - os: osx
      env:
        - TEST_SUITE=./spec/amber
        - DEPLOY_DIR=bin/darwin
        - DEPLOY_STATIC=""
    - os: osx
      env:
        - TEST_SUITE=./spec/build_spec.cr

script:
  - bin/ameba src/ $TEST_SUITE
  - crystal spec $TEST_SUITE

before_deploy:
  - mkdir -p $DEPLOY_DIR
  - crystal build src/amber/cli.cr -s --release $DEPLOY_STATIC -o $DEPLOY_DIR/amber --no-debug
  - tar -cvzf $DEPLOY_FILENAME $DEPLOY_DIR/amber

deploy:
  provider: releases
  api_key: $API_KEY
  file: $DEPLOY_FILENAME
  skip_cleanup: true
  on:
    branch: stable
    repo: amberframework/amber
    condition: $TEST_SUITE = ./spec/amber

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaf02221d4649d70b384
    on_success: change
    on_failure: always
    on_start: never
