language: crystal

services:
  - postgresql
  - redis-server

cache:
  directories:
    - bin
    - lib
    - .shards

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TEST_SUITE=./spec/amber
        - DEPLOY_DIR=bin/linux
        - STATIC_FLAG="--static"
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TEST_SUITE=./spec/build_spec.cr
    - os: osx
      env:
        - TEST_SUITE=./spec/amber
        - DEPLOY_DIR=bin/darwin
        - # NOTE: https://developer.apple.com/library/content/qa/qa1118/_index.html
        - STATIC_FLAG=""
        - PGPORT=5432
    - os: osx
      env:
        - TEST_SUITE=./spec/build_spec.cr
        - PGPORT=5432

before_script:
  - # HACK: https://apple.stackexchange.com/a/126832
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then openssl version -a; brew link openssl --force; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then openssl version -a; fi
  - # HACK: https://github.com/travis-ci/travis-ci/issues/1875
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services stop postgres; brew services start postgres; fi
  - # HACK: https://gist.github.com/subfuzion/9631143
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install redis; brew services start redis; fi

script:
  - bin/ameba src/ $TEST_SUITE
  - crystal spec $TEST_SUITE -s

before_deploy:
  - mkdir -p $DEPLOY_DIR
  - crystal build src/amber/cli.cr -s --release $STATIC_FLAG -o $DEPLOY_DIR/amber --no-debug
  - tar -cvzf $DEPLOY_FILENAME $DEPLOY_DIR/amber

deploy:
  provider: releases
  api_key: $API_KEY
  file: $DEPLOY_FILENAME
  skip_cleanup: true
  on:
    branch: stable
    repo: amberframework/amber
    condition: $TEST_SUITE = ./spec/amber

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaf02221d4649d70b384
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
